export interface UserDataType {
  name: string
  apellidoPaterno: string
  apellidoMaterno: string
  rol: string
  email: string
  phone: string
  date: string
  avatar: string
  status: string
}

export const usersData: UserDataType[] = [
  {
    name: 'Juan',
    apellidoPaterno: 'Pérez',
    apellidoMaterno: 'Gómez',
    rol: 'Administrador',
    email: 'juan.perez@gmail.com',
    phone: '+52 55 1234 5678',
    date: '22 Agosto 2024',
    status: 'Activo',
    avatar: 'assets/images/users/avatar-1.jpg',
  },
  {
    name: 'María',
    apellidoPaterno: 'López',
    apellidoMaterno: 'Martínez',
    rol: 'Contador',
    email: 'maria.lopez@gmail.com',
    phone: '+52 81 2345 6789',
    date: '20 Agosto 2024',
    status: 'Activo',
    avatar: 'assets/images/users/avatar-3.jpg',
  },
  {
    name: 'José',
    apellidoPaterno: 'Ramírez',
    apellidoMaterno: 'Sánchez',
    rol: 'Administrador',
    email: 'jose.ramirez@gmail.com',
    phone: '+52 33 9876 5432',
    date: '15 Agosto 2024',
    status: 'Activo',
    avatar: 'assets/images/users/avatar-3.jpg',
  },
  {
    name: 'Ana',
    apellidoPaterno: 'González',
    apellidoMaterno: 'Fernández',
    rol: 'Contador',
    email: 'ana.gonzalez@gmail.com',
    phone: '+52 55 7654 3210',
    date: '08 Agosto 2024',
    status: 'Inactivo',
    avatar: 'assets/images/users/avatar-4.jpg',
  },
  {
    name: 'Carlos',
    apellidoPaterno: 'Herrera',
    apellidoMaterno: 'Ruiz',
    rol: 'Administrador',
    email: 'carlos.herrera@gmail.com',
    phone: '+52 81 5432 1098',
    date: '02 Agosto 2024',
    status: 'Activo',
    avatar: 'assets/images/users/avatar-5.jpg',
  },
  {
    name: 'Sofía',
    apellidoPaterno: 'Méndez',
    apellidoMaterno: 'Castillo',
    rol: 'Contador',
    email: 'sofia.mendez@gmail.com',
    phone: '+52 33 6789 4321',
    date: '28 Julio 2024',
    status: 'Inactivo',
    avatar: 'assets/images/users/avatar-1.jpg',
  },
  {
    name: 'Ricardo',
    apellidoPaterno: 'Torres',
    apellidoMaterno: 'Vargas',
    rol: 'Administrador',
    email: 'ricardo.torres@gmail.com',
    phone: '+52 55 8765 2109',
    date: '19 Julio 2024',
    status: 'Activo',
    avatar: 'assets/images/users/avatar-6.jpg',
  },
  {
    name: 'Fernanda',
    apellidoPaterno: 'Rojas',
    apellidoMaterno: 'Navarro',
    rol: 'Contador',
    email: 'fernanda.rojas@gmail.com',
    phone: '+52 81 2345 6789',
    date: '14 Julio 2024',
    status: 'Activo',
    avatar: 'assets/images/users/avatar-3.jpg',
  },
  {
    name: 'Luis',
    apellidoPaterno: 'Castro',
    apellidoMaterno: 'Ortega',
    rol: 'Administrador',
    email: 'luis.castro@gmail.com',
    phone: '+52 33 5432 6789',
    date: '10 Julio 2024',
    status: 'Activo',
    avatar: 'assets/images/users/avatar-4.jpg',
  },
  {
    name: 'Gabriela',
    apellidoPaterno: 'Vargas',
    apellidoMaterno: 'Molina',
    rol: 'Contador',
    email: 'gabriela.vargas@gmail.com',
    phone: '+52 55 6789 1234',
    date: '21 Junio 2024',
    status: 'Inactivo',
    avatar: 'assets/images/users/avatar-5.jpg',
  },
  {
    name: 'Pablo',
    apellidoPaterno: 'Jiménez',
    apellidoMaterno: 'Delgado',
    rol: 'Administrador',
    email: 'pablo.jimenez@gmail.com',
    phone: '+52 81 2109 8765',
    date: '12 Junio 2024',
    status: 'Activo',
    avatar: 'assets/images/users/avatar-1.jpg',
  },
  {
    name: 'Alejandra',
    apellidoPaterno: 'Cruz',
    apellidoMaterno: 'Aguilar',
    rol: 'Contador',
    email: 'alejandra.cruz@gmail.com',
    phone: '+52 33 1098 6543',
    date: '17 Mayo 2024',
    status: 'Inactivo',
    avatar: 'assets/images/users/avatar-4.jpg',
  },
  {
    name: 'Martín',
    apellidoPaterno: 'Salazar',
    apellidoMaterno: 'Mejía',
    rol: 'Administrador',
    email: 'martin.salazar@gmail.com',
    phone: '+52 55 6543 7890',
    date: '07 Mayo 2024',
    status: 'Activo',
    avatar: 'assets/images/users/avatar-3.jpg',
  },
]
